Rename invalid class and fieldnames
xenit-eu/contentcloud-scribe pull request #48
Opened 2022-07-06 16:23 UTC by tgeens

2022-07-06 16:41 UTC, vierbergenlars requested changes

2022-07-06 16:41 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +                                        .replaceAll("\\d+|\\D+", "$0-")
If you do it the other way around (first replace letter segments with an appended dash), you don't have to split twice.

2022-07-06 16:41 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +                                        .replaceAll("\\d+|\\D+", "$0-")
Also, this breaks the assumption that there are no empty segments: If a field ends with a number, the last segment will be empty.

2022-07-06 16:41 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +                                        .replaceAll("\\d+|\\D+", "$0-")
Turn the comment (or regex around), so the "letter & number" explanation matches with the order of matching in the regex.

2022-07-06 16:41 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntityProperty.java
> +        public static String normalized(String source) {
Shouldn't this be a private method?

2022-07-06 16:41 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntityProperty.java
> +            return source.replaceAll("-", "").toLowerCase(Locale.ROOT);
This normalizes the field name by removing dashes and lowercasing.
But the normalized field name is also used to generate the names for a content property (through `JpaEntityProperty#canonicalName()`), which would then lead to inconsistency in how plain entity properties are named and how content properties are named.

2022-07-07 07:43 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +                                        .replaceAll("\\d+|\\D+", "$0-")
> If you do it the other way around (first replace letter segments with an appended dash), you don't have to split twice.
That was my first approach, but then I had to handle the special case were you end up with double hypens `--`

> Also, this breaks the assumption that there are no empty segments: If a field ends with a number, the last segment will be empty.
No, `String.split(regex)` discards trailing empty strings in the resulting array. See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html#split(java.lang.String)

I'll add a test to cover that case

> Turn the comment (or regex around), so the "letter & number" explanation matches with the order of matching in the regex.
:+1:

2022-07-07 07:45 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntityProperty.java
> +            return source.replaceAll("-", "").toLowerCase(Locale.ROOT);
Right, content properties should use the original name as a base :thinking:

2022-07-07 07:55 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +                                        .replaceAll("\\d+|\\D+", "$0-")
Then agian, reconcatenating empty strings shouldn't be a problem :shrug:

2022-07-07 08:26 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntityProperty.java
> +        public static String normalized(String source) {
It is used by `JpaEntity` when removing an attribute. Made it package visible.

2022-07-07 08:29 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntityProperty.java
> +            return source.replaceAll("-", "").toLowerCase(Locale.ROOT);
renamed to `JpaEntityProperty#normailzedName()` and exposed the original name again as `JpaEntityProperty#name()`

2022-07-07 08:37 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/source/java/JpaEntityJavaSourceCodeGenerator.java
> +        var fieldSpec = FieldSpec.builder(idTypeName, idField.normalizedName(), Modifier.PRIVATE)
Should use `fieldName()`?

2022-07-07 08:37 UTC, vierbergenlars commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/source/java/JpaEntityJavaSourceCodeGenerator.java
> +        MethodSpec setter = MethodSpec.methodBuilder("set" + StringUtils.capitalize(field.normalizedName()))
Hmm, shouldn't setters & getters match the field name prepended with `set`/`get`?

Otherwise you will still get a collision for the `id` field, right?

2022-07-07 08:53 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/source/java/JpaEntityJavaSourceCodeGenerator.java
> +        var fieldSpec = FieldSpec.builder(idTypeName, idField.normalizedName(), Modifier.PRIVATE)
Right, didn't catch this because the tests all use lombok :roll_eyes:

2022-07-07 08:54 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/source/java/JpaEntityJavaSourceCodeGenerator.java
> +        MethodSpec setter = MethodSpec.methodBuilder("set" + StringUtils.capitalize(field.normalizedName()))
Right, didn't catch this because the tests all use lombok roll_eyes

2022-07-07 08:59 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/source/java/JpaEntityJavaSourceCodeGenerator.java
> +        var fieldSpec = FieldSpec.builder(idTypeName, idField.normalizedName(), Modifier.PRIVATE)
Technically correct - but in both cases it's going to be `"id"` ;-)

2022-07-07 09:02 UTC, rschev commented on scribe-generator/src/test/java/eu/xenit/contentcloud/scribe/generator/spring/data/SpringDataSourceCodeProjectContributionTest.java
> +
Maybe not for today, but it might be good to have a happy path+unhappy path test for a field named `id` as well, since that case is tricky too

2022-07-07 09:02 UTC, vierbergenlars approved these changes

2022-07-07 09:03 UTC, rschev commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +            if (name.length() < 3 || name.length() > 50) {
Oh the minimum length of 1 is only for fields.

2022-07-07 09:20 UTC, tgeens commented on scribe-generator/src/main/java/eu/xenit/contentcloud/scribe/generator/spring/data/model/jpa/JpaEntity.java
> +            if (name.length() < 3 || name.length() > 50) {
Yes, still up for discussion

2022-07-07 09:20 UTC, merged